apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-09-09T08:05:28Z
  generation: 1
  labels:
    app: haproxy-ingress-scheduler
  name: haproxy-ingress-scheduler-rc
  namespace: danieltmp
  resourceVersion: "26492568"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/haproxy-ingress-scheduler-rc
  uid: 2b9cd64a-7664-11e6-bdf8-5254c020463d
spec:
  replicas: 1
  selector:
    app: haproxy-ingress-scheduler
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: haproxy-ingress-scheduler
      name: haproxy-ingress-scheduler
    spec:
      containers:
      - args:
        - --controller-replicas=1
        - --vip-pool=10.244.101.193/28
        - --skydns-etcd-endpoints=http://localhost:2379
        image: index.caicloud.io/caicloud/haproxy-ingress-scheduler:0.0
        imagePullPolicy: Always
        name: haproxy-ingress-scheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
      - image: quay.io/coreos/etcd:v2.2.0
        imagePullPolicy: IfNotPresent
        name: skydns-etcd
        resources: {}
        terminationMessagePath: /dev/termination-log
      - args:
        - -addr
        - 0.0.0.0:53
        image: skynetservices/skydns:latest
        imagePullPolicy: IfNotPresent
        name: skydns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
